Got it working, except I have to manually refresh the window manager desktop.  Would like to be able to do this programmatically.

diff --git a/desktop b/desktop
--- a/desktop
+++ b/desktop
@@ -17,6 +17,7 @@ function usage() {
     echo
     echo "Example:"
     echo "    desktop ~/Pictures    View your pictures on the desktop"
+    echo
 }
 
 
@@ -35,51 +36,118 @@ function check_num_args() {
 function check_args_for_meta() {
     case $ARG in
     # Check if we match a "show" option
-    -l|--list|-s|--show)
+    -l|--list|-s|--show )
+    echo
     if [[ -L "$HOME/Desktop" ]]
     then
         echo "$HOME/Desktop is currently set to $(readlink $HOME/Desktop)"
+    elif [[ ! -e "$HOME/Desktop" ]]
+    then
+        echo "$HOME/Desktop does not exist"
     else
-        echo "$HOME/Desktop is a directory"
+        echo "$HOME/Desktop is not a symlink"
     fi
+    echo
     exit 0
     ;;
     # Check if we match -h --help
-    -h|--help)
+    -h|--help )
     usage
     exit 0
     esac
+}
 
-    #echo "Desktop directory switcher:  Illegal argument.  Run \`desktop -h\` to show help."
-    #exit 1
+
+# 
+function link_desktop() {
+    echo
+
+    # First check if the argument is actually a directory and
+    # If not, error message and exit
+    if [[ ! -d "$ARG" ]]
+    then
+    echo "$ARG is not a directory.  Cannot create symlink.  Aborting..."
+    echo
+    exit 4
+    fi
+
+    # If target directory 
+    if [[ ! -r "$ARG" ]]
+    then
+        echo "$ARG is not readable.  Aborting..."
+        echo
+        exit 2
+    fi
+
+    # If HOME/Desktop already exists as a symlink, delete it
+    if [[ -L "$HOME/Desktop" ]]
+    then
+        `rm -rf $HOME/Desktop`
+    # Check if the HOME/Desktop directory already exists and is readable
+    # Prompt to backup to another directory
+    # If user declines, just delete it
+    # They can also cancel the whole thing
+    elif [[ -d "$HOME/Desktop" ]] || [[ -f "$HOME/Desktop" ]]
+    then
+
+        # Prompt and actions
+        while true; do
+            echo "$HOME/Desktop already exists."
+            read -p "Would you like to make a backup first?  (Y)es, (n)o, (c)ancel:  " response
+            case $response in
+                # Cancelling - just exit
+                c|cancel )
+                echo "Exiting..."
+                echo
+                exit 0
+                ;;
+                # Yes - Create backup
+                Y|Yes )
+                echo "Moving $HOME/Desktop to $HOME/Desktop_OLD"
+                `mv $HOME/Desktop $HOME/Desktop_OLD`
+                if [[ ! $? -eq 0 ]]
+                then
+                    echo "Error creating backup.  Aborting..."
+                    exit 3
+                fi
+                break
+                ;;
+                # No - Do not create backup, but proceed anyway
+                n|no )
+                break
+                ;;
+                # Any other input - will go back to top of loop
+                * )
+                echo "Invalid selection"
+                ;;
+            esac
+        done
+    fi
+
+    # Check if target directory is writable
+    # If not, display warning message, but continue anyway
+    if [[ ! -w "$ARG" ]]
+    then
+        echo "** Warning: $ARG is not writable, so you will not be able"
+        echo "            to create/modify/delete files on the desktop."
+    fi
+
+    # Create new symlink from HOME/Desktop to destination directory
+    `ln -s $ARG $HOME/Desktop`
+    echo
+    echo "$HOME/Desktop symlinked to $ARG"
+    echo
 }
 
 
 
-# Start script
+#
+# Execute script
+#
+
 NUM_ARGS=$#
 ARG=$1
+
 check_num_args
-
 check_args_for_meta
-
-
-
-# If we make it this far, try to make the switch
-
-# First check if the HOME/Desktop directory already exists
-# Prompt to backup to another directory
-# If user declines, exit
-
-# Check if the argument is actually a directory and
-# If not, error message and exit
-
-# If so, check if readable
-# If not, error message and exit
-
-# Check if writable
-# If not, display warning message, but continue anyway
-
-# If HOME/Desktop already exists as a symlink, delete it
-
-# Create new symlink from HOME/Desktop to destination directory
+link_desktop
